/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author juanb
 */
public class Vistas extends javax.swing.JFrame {

    /**
     * Creates new form Vistas
     */
    public Vistas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JMenuBar();
        alumnobar = new javax.swing.JMenu();
        formalumno = new javax.swing.JMenuItem();
        materiabar = new javax.swing.JMenu();
        formmateria = new javax.swing.JMenuItem();
        adminbar = new javax.swing.JMenu();
        forminsc = new javax.swing.JMenuItem();
        formnotas = new javax.swing.JMenuItem();
        consultasbar = new javax.swing.JMenu();
        formalumnoxmateria = new javax.swing.JMenuItem();
        salirbar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        alumnobar.setText("Alumno");

        formalumno.setText("Formulario de alumno");
        formalumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formalumnoActionPerformed(evt);
            }
        });
        alumnobar.add(formalumno);

        menu.add(alumnobar);

        materiabar.setText("Materia");

        formmateria.setText("Fromulario de materia");
        formmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formmateriaActionPerformed(evt);
            }
        });
        materiabar.add(formmateria);

        menu.add(materiabar);

        adminbar.setText("Admininstracion");

        forminsc.setText("Manejo de inscripciones");
        forminsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forminscActionPerformed(evt);
            }
        });
        adminbar.add(forminsc);

        formnotas.setText("Manipulacion de notas");
        formnotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formnotasActionPerformed(evt);
            }
        });
        adminbar.add(formnotas);

        menu.add(adminbar);

        consultasbar.setText("Consultas");

        formalumnoxmateria.setText("Alumnos por materia");
        formalumnoxmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formalumnoxmateriaActionPerformed(evt);
            }
        });
        consultasbar.add(formalumnoxmateria);

        menu.add(consultasbar);

        salirbar.setText("Salir");
        salirbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirbarActionPerformed(evt);
            }
        });
        menu.add(salirbar);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formalumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formalumnoActionPerformed
        // TODO add your handling code here:
        AlumnoVista alumno = new AlumnoVista();
        jPanel1.add(alumno);
        alumno.setVisible(true);
        alumno.setMaximizable(true);
    }//GEN-LAST:event_formalumnoActionPerformed

    private void formmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formmateriaActionPerformed
        // TODO add your handling code here:
        MateriaVista materia = new MateriaVista();
        jPanel1.add(materia);
        materia.setVisible(true);
        materia.setMaximizable(true);
    }//GEN-LAST:event_formmateriaActionPerformed

    private void forminscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forminscActionPerformed
        // TODO add your handling code here:
        FormularioInscripcion inscripcion = new FormularioInscripcion();
        jPanel1.add(inscripcion);
        inscripcion.setVisible(true);
        inscripcion.setMaximizable(true);
        
    }//GEN-LAST:event_forminscActionPerformed

    private void formnotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formnotasActionPerformed
        // TODO add your handling code here:
        Notas nota = new Notas();
        jPanel1.add(nota);
        nota.setVisible(true);
        nota.setMaximizable(true);
        
    }//GEN-LAST:event_formnotasActionPerformed

    private void formalumnoxmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formalumnoxmateriaActionPerformed
        // TODO add your handling code here:
        AlumnosXMaterias consulta = new AlumnosXMaterias();
        jPanel1.add(consulta);
        consulta.setVisible(true);
        consulta.setMaximizable(true);
    }//GEN-LAST:event_formalumnoxmateriaActionPerformed

    private void salirbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirbarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_salirbarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vistas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vistas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu adminbar;
    private javax.swing.JMenu alumnobar;
    private javax.swing.JMenu consultasbar;
    private javax.swing.JMenuItem formalumno;
    private javax.swing.JMenuItem formalumnoxmateria;
    private javax.swing.JMenuItem forminsc;
    private javax.swing.JMenuItem formmateria;
    private javax.swing.JMenuItem formnotas;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JMenu materiabar;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu salirbar;
    // End of variables declaration//GEN-END:variables
}
